server:
  port: 8888
#  改变根路径,项目访问路径
  servlet:
    context-path: /aaa

user:
  name: oo
  age: 19

spring:
  # 开发环境禁用thymeleaf模板缓存
  thymeleaf:
    cache: false
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    # druid相关配置
    druid:
      # 监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 基本属性
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: jie123987
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'X'
      # 空闲连接是否被回收
      test-while-idle: true
      # 申请连接时是否检测有效性
      test-on-borrow: false
      # 归还连接时是否检测有效性
      test-on-return: false
  redis:
    host: 127.0.0.1
    port: 6379
    client-name: root


mybatis:
  # 配置本地Mapper.xml的映射路径
  mapper-locations: classpath:cn/uaj/springboot_01/mapper/*.xml
  # mybatis自身的xml配置信息
  # config-location: classpath:cn/uaj/springboot_01/mybatis/mybatis-config.xml
  # 配置实体模型路径，完成自动类名转换
  type-aliases-package: cn.uaj.springboot_01.entity
# 配置分页参数合理化
pagehelper:
  reasonable: reasonable=true


