server:
  port: 8080
  servlet:
    context-path: /

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer # JWT负载中拿到开头
spring:
  profiles:
    active: dev #默认为开发环境
  data:
    mongodb:
      host: localhost # mongodb的连接地址
      port: 27017 # mongodb的连接端口
      database: adminmaster-port  # mongodb的连接的数据库
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /adminmaster # rabbitmq的虚拟host
    username: jie # rabbitmq的用户名
    password: 123 # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置未true


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:cn/**/mapper/*.xml
  # 配置实体模型路径，完成自动类名转换
  type-aliases-package: cn.uaj.adminmaster.mbg.model
